protected/modules/main/models/MainPages.php
<?php

/**
 * This is the model class for table "pages".
 *
 * The followings are the available columns in table 'pages':
 * @property integer $id
 * @property string $title_ru
 * @property string $title_ro
 * @property string $footer_title_ru
 * @property string $footer_title_ro
 * @property string $content_ru
 * @property string $content_ro
 * @property string $slug
 */
class MainPages extends ActiveRecord
{
	/**
	 * Returns the static model of the specified AR class.
	 * @param string $className active record class name.
	 * @return Pages the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'main_pages';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('title_ru, title_ro, content_ru, content_ro, slug', 'required'),
			array('title_ru, title_ro, slug, footer_title_ru, footer_title_ro', 'length', 'max'=>255),
            array('title_image', 'file', 'types'=>'jpg, gif, png, jpeg', 'allowEmpty'=>true, 'safe' => false),
            array('meta_title_ru, meta_title_ro, meta_keywords_ru, meta_keywords_ro, meta_description_ru, meta_description_ro, meta_header_ru, meta_header_ro', 'length', 'max'=>250),
            array('ogimage', 'file', 'types'=>'jpg, gif, png, jpeg', 'allowEmpty'=>true, 'safe' => false),
            array('slug', 'unique'),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('id, title_ru, title_ro, content_ru, content_ro, slug, meta_title_ru, meta_title_ro, meta_keywords_ru, meta_keywords_ro, meta_description_ru, meta_description_ro, meta_header_ru, meta_header_ro', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'title_ru' => 'Title Ru',
            'title_ro' => 'Title Ro',
			'content_ru' => 'Content Ru',
            'content_ro' => 'Content Ro',
			'slug' => 'Slug',
                        'meta_title_ru' => 'Meta Title',
                        'meta_title_ro' => 'Meta Title',
                        'meta_keywords_ru' => 'Meta Keywords',
                        'meta_keywords_ro' => 'Meta Keywords',
                        'meta_description_ru' => 'Meta Description',
                        'meta_description_ro' => 'Meta Description',
                        'meta_header_ru' => 'Meta Header',
                        'meta_header_ro' => 'Meta Header',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('title_ru',$this->title_ru,true);
        $criteria->compare('title_ro',$this->title_ro,true);
		$criteria->compare('content_ru',$this->content_ru,true);
        $criteria->compare('content_ro',$this->content_ro,true);
		$criteria->compare('slug',$this->slug,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

    public function getTitle() {
        return $this->{'title_' . Yii::app()->language};
    }

    public function getFooterTitle() {
        return $this->{'footer_title_' . Yii::app()->language} ? : $this->getTitle();
    }

    public function getContent() {
        return $this->{'content_' . Yii::app()->language};
    }

    public function getMetaTitle() {
        return $this->{'meta_title_' . Yii::app()->language} ?: $this->{'title_' . Yii::app()->language};
    }

    public function getMetaKeyword() {
        return $this->{'meta_keywords_' . Yii::app()->language};
    }

    public function getMetaDescription() {
        return $this->{'meta_description_' . Yii::app()->language};
    }

    public function getUrl() {
        return Yii::app()->createUrl('/main/default/page', array('id' => $this->id));
    }
}

protected/modules/main/controllers/DefaultController.php
<?php
class DefaultController extends Frontend
{
    /**
     * Declares class-based actions.
     */
    public function actions()
    {
        return array(
            // captcha action renders the CAPTCHA image displayed on the contact page
            'captcha'=>array(
                'class'=>'CCaptchaAction',
                'backColor'=>0xFFFFFF,
            ),
            // page action renders "static" pages stored under 'protected/views/site/pages'
            // They can be accessed via: index.php?r=site/page&view=FileName
            'page'=>array(
                'class'=>'CViewAction',
            ),
            'webhook' => 'application.components.Webhook',
        );
    }

    public function actionChange()
    {
        if (isset($_GET['lang'])) {
            Yii::app()->session['language'] = $_GET['lang'];
        }
        if (isset(Yii::app()->session['language'])) {
            $cookie = new CHttpCookie('language', $_GET['lang']);
            $cookie->expire = time() + (60*60*24*365); // (1 year)
            Yii::app()->request->cookies['language'] = $cookie;

            Yii::app()->language = Yii::app()->session['language'];
            Yii::app()->user->setState('language', $_GET['lang']);
        }
        $baseUrl = Yii::app()->request->getBaseUrl(true)."/";
        $refferer = Yii::app()->request->urlReferrer;
        $expl_refer = explode('/', $refferer);

        if ($baseUrl==$refferer || in_array(end($expl_refer), Yii::app()->languages->languages)) {
            $link = $this->createUrl("/main/default/index", array("lang"=>Yii::app()->language));
            if ($link == '/') {
                $link = $link . Yii::app()->language;
            }
            $this->redirect($link);
        } else {
            $this->redirect($this->urltrans(Yii::app()->request->urlReferrer));
        }
    }

    /**
     * This is the default 'index' action that is invoked
     * when an action is not explicitly requested by users.
     */
    public function actionIndex()
    {
        if (Yii::app()->language != Yii::app()->user->language) {
            $this->redirect('/' . Yii::app()->user->language);
        }
        $this->render('index');
    }

    public function actionFeedback()
    {
        $model = new MainFeedback();
        $model->scenario = 'registerwcaptcha';

        /*if (isset($_POST['ajax']) && $_POST['ajax'] === 'feedback-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }*/

        if (isset($_POST["MainFeedback"])) {
            $model->attributes = $_POST["MainFeedback"];

            if($model->save()) {
                if($this->sendMailContact($model)){
                    Yii::app()->getUser()->setFlash(
                        FlashMessages::SUCCESS_MESSAGE(),
                        YHelper::yiisetting('success_message_contact_'.Yii::app()->language)
                    );
                    $model->unsetAttributes();
                }else{
                    throw new CException("Error on send email!");
                }
            }
        }

        $this->render('feedback', array('model' => $model));
    }

    public function sendMailContact($model){
        $emails_settings = YHelper::yiisetting('emails_list_contact');
        if($emails_settings){
            $mailer = Yii::createComponent('application.extensions.mailer.EMailer');
            $mailer->AddReplyTo($model->email);
            $emails_arr = preg_split("/\\r\\n|\\r|\\n/", $emails_settings);
            foreach($emails_arr as $email){
                $mailer->AddAddress($email);
            }
            $mailer->FromName = Yii::app()->name;
            $mailer->CharSet = 'UTF-8';
            $mailer->Subject = "Сообщение со страницы контактов с сайта ".Yii::app()->name;
            $mailer->IsHTML(true);  // set email format to HTML
            $body = "Сообщение со страницы контактов с сайта ".Yii::app()->name."<br><br>"
                    . "Имя: {$model->name} <br>"
                    . "Email: {$model->email} <br>"
                    . "Сообщение: {$model->feedback} <br>";
            $mailer->Body = $body;

            if($mailer->Send()) {
                return true;
            } else {
                return false;
            }
        }
        return true;
    }

    public function actionPage($id){
        $model = MainPages::model()->findByPk($id);
        if(!$model)
            throw new CHttpException(404,Yii::t("base","The requested page does not exist!"));

        $this->render("page",array('model'=>$model));
    }

    public function actionPartners(){
        $this->render("partners");
    }

    public function actionCalculator(){
        $this->render("calculator");
    }

    public function actionDownload(){
        $filepath = 'files/document.txt';

        $fpath = explode("/", $filepath);
        $fileName = end($fpath);

        if (file_exists($filepath))
            return Yii::app()->getRequest()->sendFile($fileName, @file_get_contents($filepath));
        else
            throw new CHttpException(404, 'This file does not exist.');
    }

    /**
     * This is the action to handle external exceptions.
     */
    public function actionError()
    {
        if($error=Yii::app()->errorHandler->error)
        {
            if(Yii::app()->request->isAjaxRequest)
                echo $error['message'];
            else
                $this->render('error', $error);
        }
    }

    public function actionPriceCount()
    {
        $model = new PriceCount();

        if (isset($_POST['PriceCount'])) {
            $model->attributes=$_POST['PriceCount'];
            if ($model->validate()) {
                $blogArticle = $_FILES['PriceCount'];

                $theme = 'DASLIGHT расчет стоймости';
                $body = $this->renderPartial('main.views.default._email', ['model' => $model], true);
                Yii::app()->email->sendEmail($theme, $body, YHelper::yiisetting('email'), $model->email, $blogArticle);

                Yii::app()->getUser()->setFlash(
                    FlashMessages::SUCCESS_MESSAGE(),
                    YHelper::yiisetting('success_message_calculation_'.Yii::app()->language)
                );

                $this->refresh(true);
            }
        }

        $this->render('price_count',array(
            'model'=>$model,
        ));
    }
}

protected/modules/main/views/default/_menu.php
<li>
    <a class="" href="<?php echo Yii::app()->controller->createUrl('/main/default/index', array('lang' => Yii::app()->language)); ?><?php //echo Yii::app()->homeUrl; ?>">
        <?php echo Yii::t("base", "Main");?>
    </a>
</li>
<!-- Start Product menu dropdown -->
<?php $this->widget('main.widgets.ProductMenu'); ?>
<!-- End Product menu dropdown -->
<li>
    <a href="<?php echo $this->createUrl('/main/default/priceCount'); ?>">
        <?php echo Yii::t("base", "Shares");?>
    </a>
</li>
<li>
    <a href="<?php echo $this->createUrl('/blog/frontBlog/category', array('id' => 1)); ?>">
        <?php echo Yii::t("base", "About light-emitting diodes");?>
    </a>
</li>
<li>
    <a href="<?php echo $this->createUrl('/main/default/page', array('id' => 2)); ?>">
        <?php echo Yii::t("base", "About company");?>
    </a>
</li>
<li>
    <a href="<?php echo $this->createUrl('/blog/frontBlog/category', array('id' => 7)); ?>">
        <?php echo Yii::t("base", "Our projects");?>
    </a>
</li>
<li>
    <a href="<?php echo $this->createUrl('/main/default/feedback'); ?>"><?php echo Yii::t("base", "Contacts");?></a>
</li>

protected/modules/main/views/default/error.php
<?php
/* @var $this SiteController */
/* @var $error array */

$this->pageTitle=Yii::app()->name . ' - Error';
$this->breadcrumbs=array(
	'Error',
);
?>

<div class="row">
    <div class="col-md-12">
        <p class="text-center">
            <span class="text-info" style="font-size:4em;">Error <?php echo $code; ?></span><br />
            <span class="text-info" style="font-size:1em;"><?php echo CHtml::encode($message); ?></span>
        </p>
        <p class="text-center">It looks like you have taken a wrong turn</p>
        <p class="text-center">If you are in denial and think it's a conspiracy that cannot possibly be true,</br>try using the search bar below.</p>
    </div>
</div>

protected/modules/main/views/default/feedback.php
<section class="mt-contact-banner mt-banner-22 wow fadeInUp" data-wow-delay="0.4s" >
    <div class="promo-image" style="background-image: url('/static/images/contacts.jpg');">
    <div class="container">
        <div class="row">
            <div class="col-xs-6 col-sm-12 text-left-xs text-center-sm ">
                <h1 class="cart-page">
                    <?php echo Yii::t("base", "Contacts"); ?>
                </h1>
                <?php $this->widget('Breadcrumbs', array(
                    'links'=>array(
                        Yii::t("base", "Contacts")
                    ),
                )); ?>
            </div>
        </div>
    </div>
    </div>
</section>

<div class="mt-bestseller text-center wow fadeInUp" data-wow-delay="0.4s" style="visibility: visible; animation-delay: 0.4s; animation-name: fadeInUp;">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 page-text text-left">
                <p>
                <div style="height: 450px; width: 100%;">
                    <?php Yii::app()->GM->f()?>
                </div>
                <!--<iframe width="100%" height="450" frameborder="0" allowfullscreen="" style="border:0" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2721.3939169088208!2d28.844259350146462!3d46.99323783803861!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x40c97eb010b8eef7%3A0x2932f2ac1d16e9bf!2sBulevardul+Dacia+2%2C+Chi%C5%9Fin%C4%83u%2C+Moldova!5e0!3m2!1sen!2s!4v1447418081651" class="mb30 mt10"></iframe>-->
                <div class="row">
                    <br>
                    <?php $this->widget('ContactinfoWidget'); ?>
                    <div class="col-lg-12 pb10">
                        <?php $form = $this->beginWidget('CActiveForm', array(
                            'id' => 'feedback-form',
                            'enableAjaxValidation' => false,
                            'clientOptions' => array(
                                'validateOnSubmit' => true,
                                'validateOnChange' => false,
                                'inputContainer' => 'fieldset',
                            ),
                        )); ?>
                        <h5><?php echo Yii::t("MainModule.main", "Contact form");?></h5>
                        <div class="pb10">
                            <?php echo $form->textField($model, 'name', array('class' => 'form-control', 'placeholder' => Yii::t("MainModule.main", "Name"))); ?>
                            <?php echo $form->error($model, 'name'); ?>
                        </div>
                        <div class="pb10">
                            <?php echo $form->textField($model, 'email', array('class' => 'form-control', 'placeholder' => Yii::t("MainModule.main", "Email"))); ?>
                            <?php echo $form->error($model, 'email'); ?>
                        </div>
                        <div class="pb10">
                            <?php echo $form->textArea($model, 'feedback', array('class' => 'form-control', 'rows' => 8, 'placeholder' => Yii::t("MainModule.main", "Message"))); ?>
                            <?php echo $form->error($model, 'feedback'); ?>
                        </div>
                        <div class="pb10">
                            <?php $this->widget('application.extensions.recaptcha.EReCaptcha',
                                array('model'=>$model, 'attribute'=>'validacion',
                                    'theme'=>'red', 'language'=>'en_EN',
                                    'publicKey'=>'6LfVThcTAAAAAAzyzRI3-0SZ_L2g4zw1K6t5Gok3')) ?>
                            <?php echo CHtml::error($model, 'validacion'); ?>
                        </div>
                        <div class="text-right">
                            <button class="button-inline button-green" type="submit"><?php echo Yii::t("MainModule.main", "Send");?></button>
                        </div>
                        <?php $this->endWidget(); ?>
                    </div>
                </div>
                </p>
            </div>
        </div>
    </div>
</div>

protected/modules/main/views/default/index.php
<?php
//    if (Yii::app()->language == 'ro'){
//        $this->pageTitle = 'DASLight - iluminarea LED Nr1 în Moldova';
//        $this->metaDescription = 'DASLight oferă o gamă largă de becuri LED, benzi cu LED-uri, profile de aluminiu, precum și servicii de instalare.';
//    } else {
//        $this->pageTitle = 'DASLight - LED освещение Nr1 в Молдове';
//        $this->metaDescription = 'Компания DASLight предлагает богатый ассортимент LED ламп, светодиодных лент, аллюминевых профилей, а также услуги по их установке.';
//    }
    $this->pageTitle = YHelper::yiisetting('meta_title_'.Yii::app()->language);
    $this->metaKeywords = YHelper::yiisetting('meta_keywords_'.Yii::app()->language);
    $this->metaDescription = YHelper::yiisetting('meta_description_'.Yii::app()->language);
    $this->ogImage = 'static/images/daslogo.png';
    $this->ogUrl = Yii::app()->request->requestUri;
?>

<?php $this->widget('MainCategories'); ?>

protected/modules/main/views/default/page.php
<section class="mt-contact-banner mt-banner-22 wow fadeInUp" data-wow-delay="0.4s" >
    <div class="promo-image" style="background-image: url('<?php echo YHelper::getImagePath($model->title_image,0,0, Yii::app()->params['header_image']); ?>');">
        <div class="container">
            <div class="row">
                <div class="col-xs-6 col-sm-12 text-left-xs text-center-sm">
                    <h1 class="cart-page">
                        <?php echo $model->{"meta_header_".Yii::app()->language} ?: $model->{"title_".Yii::app()->language}; ?>
                    </h1>
                    <?php $this->widget('Breadcrumbs', array(
                        'links'=>array(
                            $model->{"meta_header_".Yii::app()->language} ?: $model->{"title_".Yii::app()->language}
                        ),
                    )); ?>
                </div>
            </div>
        </div>
    </div>
</section>

<div class="mt-bestseller text-center wow fadeInUp" data-wow-delay="0.4s" style="visibility: visible; animation-delay: 0.4s; animation-name: fadeInUp;">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 page-text text-left">
                <p><?php echo $model->content; ?></p>
            </div>
        </div>
    </div>
</div>

protected/modules/main/views/default/partners.php
<section class="mt-contact-banner mt-banner-22 wow fadeInUp" data-wow-delay="0.4s">
    <div class="promo-image" style="background-image: url('/static/images/contacts.jpg');">
    <div class="container">
        <div class="row">
            <div class="col-xs-6 col-sm-12 text-left-xs text-center-sm">
                <h1 class="cart-page">
                    <?php echo YHelper::yiisetting('partners_title_'.Yii::app()->language); ?>
                </h1>
                <?php $this->widget('Breadcrumbs', array(
                    'links'=>array(
                        YHelper::yiisetting('partners_title_'.Yii::app()->language)
                    ),
                )); ?>
            </div>
        </div>
    </div>
    </div>
</section>

<div class="pt-5em pb-5em text-center wow fadeInUp" data-wow-delay="0.4s" style="visibility: visible; animation-delay: 0.4s; animation-name: fadeInUp;">
    <div class="container">
        <?php echo YHelper::yiisetting('partners_'.Yii::app()->language); ?>
    </div>
</div>